version: "2"

services:
  bot:
    build: .
    restart: always
    env_file: .env
    links: ["postgres"]
    depends_on: ["postgres"]
    environment:
      DB_URI: postgres://root:password@postgres:5432/starpins

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: starpins
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432  # Do not allow this port through your firewall!
